name: Update Daily Message

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch a random programming quote
        id: fetch_quote
        run: |
          curl -s https://programming-quotes-api.herokuapp.com/quotes/random | jq -r '.en' > quote.txt

      - name: Update README
        run: |
          quote=$(cat quote.txt)
          escaped_quote="${quote//'%'/'%25'}"
          escaped_quote="${escaped_quote//$'\n'/'%0A'}"
          escaped_quote="${escaped_quote//$'\r'/'%0D'}"
          sed -i '/<!-- DAILY-CODE-MESSAGE -->/c\<!-- DAILY-CODE-MESSAGE -->\n\n$escaped_quote' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update daily message'
          git push
